# Generated by Django 6.0.1 on 2026-01-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('job_title', models.CharField(max_length=1000)),
                ('company', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('salary', models.IntegerField()),
                ('status', models.CharField(choices=[('Applied', 'applied'), ('Interview', 'interview'), ('Offer', 'offer'), ('Rejected', 'rejected')], default='Applied', max_length=25)),
            ],
        ),
    ]
